shadow = false;
shadow-radius = 0;
shadow-opacity = 0
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-color = "#000000"

fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5
no-fading-openclose = false
no-fading-destroyed-argb = false

backend = "glx"

dithered-present = false;
vsync = true;

blur:
	{
		method = "gaussian";
		size = 10;
		deviation = 10;
	}

rules: (

	{
		shadow = false;
		blur-background = false;
		fade = false;
	},
	{
		match = "window_type = 'normal'";
		fade = true;	
		shadow = false;	
        opacity = 1;
        blur-background = false;
		corner-radius = 0;
	},

	{
		match = "window_type = 'dialog'";
		shadow = false;	#-shadow-switch
	},

	{
		match = "window_type = 'tooltip'";
		corner-radius = 0;
		opacity = 1.0;
	},

    {
		match = "fullscreen";
		corner-radius = 0;
	},

	{
		match = "window_type = 'dock'";
		corner-radius = 0;
		fade = true;
	},
    {
		match = "class_g = 'st-256color'";
		opacity = 0.9;
		blur-background = false;
	},
    {
		match = "class_g = 'Dunst'";
		blur-background = false;
	},
	{
		match = "window_type = 'dropdown_menu' || window_type = 'menu' || window_type = 'popup' || window_type = 'popup_menu'";
		corner-radius = 0;
	},

    {
        match = "window_type = 'menu' || role = 'popup' || role = 'bubble'";
        shadow = false;
    },
	{
		match = "class_g = 'bspwm-scratch' || class_g = 'Updating'";
		opacity = 1.0;
		blur-background = false;	#-blur-switch
	},

 @include "picom-animations.conf"

)
