theme = "milo"

[editor]
mouse = true
auto-save = false
cursorline = true
cursorcolumn = true
bufferline = "always"
true-color = true
line-number = "relative"
scrolloff = 999
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.soft-wrap]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = []
center = []
right = []
separator = " - "
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = false
auto-signature-help = false

[editor.indent-guides]
render = true
character = ""

[editor.file-picker]
hidden = false
ignore = true

[keys.normal]
"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"
"A-w" = ":buffer-close"
y = ":clipboard-yank"
p = "paste_clipboard_after"
P = "paste_clipboard_before"

[keys.select]
y = ":clipboard-yank"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
