osd-font='IosevkaTerm NF'     
osd-font-size=20
osd-color='#FFFFFF'
osd-back-color='#00000080'
osd-bar-border-size=2
osd-bar-w=100

# Subtitles
sub-font='Iosevka Nerd Font'
sub-font-size=30
sub-color='#FFFFFF'
sub-border-size=0
sub-shadow-offset=0
sub-back-color='#00000080'

osc=no
hwdec=vaapi
vo=gpu
gpu-context=x11egl

vd-lavc-threads=16
cache=yes
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=100MiB

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
background=1
